"""Generate a comprehensive beer SKU portfolio Excel file for upload testing."""

import pandas as pd

skus = [
    # ── AB InBev ──────────────────────────────────────────────────────────
    # Budweiser
    {"sku_id": "ABI001", "manufacturer": "AB InBev", "brand": "Budweiser", "sku_name": "Budweiser 330ml Can", "price_segment": "Core", "current_price_per_unit": 1.20, "elasticity": -2.1, "cannibalization_rate": 0.12, "profit_pct_per_ml": 0.18, "volume_2025_units": 1200000, "unit_volume_ml": 330, "competitor_sku_1": "ABI002", "competitor_sku_2": "ABI003"},
    {"sku_id": "ABI002", "manufacturer": "AB InBev", "brand": "Budweiser", "sku_name": "Budweiser 500ml Can", "price_segment": "Core", "current_price_per_unit": 1.75, "elasticity": -1.8, "cannibalization_rate": 0.10, "profit_pct_per_ml": 0.19, "volume_2025_units": 900000, "unit_volume_ml": 500, "competitor_sku_1": "ABI001", "competitor_sku_2": "ABI004"},
    {"sku_id": "ABI003", "manufacturer": "AB InBev", "brand": "Budweiser", "sku_name": "Budweiser 660ml Bottle", "price_segment": "Core", "current_price_per_unit": 2.10, "elasticity": -1.6, "cannibalization_rate": 0.09, "profit_pct_per_ml": 0.17, "volume_2025_units": 450000, "unit_volume_ml": 660, "competitor_sku_1": "ABI001", "competitor_sku_2": "ABI002"},
    {"sku_id": "ABI004", "manufacturer": "AB InBev", "brand": "Budweiser", "sku_name": "Bud Light 330ml Can", "price_segment": "Value", "current_price_per_unit": 1.00, "elasticity": -2.4, "cannibalization_rate": 0.14, "profit_pct_per_ml": 0.15, "volume_2025_units": 800000, "unit_volume_ml": 330, "competitor_sku_1": "ABI001", "competitor_sku_2": "ABI005"},
    # Stella Artois
    {"sku_id": "ABI005", "manufacturer": "AB InBev", "brand": "Stella Artois", "sku_name": "Stella Artois 330ml Can", "price_segment": "Premium", "current_price_per_unit": 1.60, "elasticity": -1.5, "cannibalization_rate": 0.08, "profit_pct_per_ml": 0.22, "volume_2025_units": 800000, "unit_volume_ml": 330, "competitor_sku_1": "ABI006", "competitor_sku_2": "ABI001"},
    {"sku_id": "ABI006", "manufacturer": "AB InBev", "brand": "Stella Artois", "sku_name": "Stella Artois 660ml Bottle", "price_segment": "Premium", "current_price_per_unit": 2.80, "elasticity": -1.3, "cannibalization_rate": 0.06, "profit_pct_per_ml": 0.24, "volume_2025_units": 400000, "unit_volume_ml": 660, "competitor_sku_1": "ABI005", "competitor_sku_2": "ABI007"},
    {"sku_id": "ABI007", "manufacturer": "AB InBev", "brand": "Stella Artois", "sku_name": "Stella Artois 284ml Draught Can", "price_segment": "Premium", "current_price_per_unit": 1.90, "elasticity": -1.4, "cannibalization_rate": 0.07, "profit_pct_per_ml": 0.23, "volume_2025_units": 350000, "unit_volume_ml": 284, "competitor_sku_1": "ABI005", "competitor_sku_2": "ABI006"},
    # Beck's
    {"sku_id": "ABI008", "manufacturer": "AB InBev", "brand": "Beck's", "sku_name": "Beck's 275ml Bottle", "price_segment": "Value", "current_price_per_unit": 0.95, "elasticity": -2.5, "cannibalization_rate": 0.15, "profit_pct_per_ml": 0.14, "volume_2025_units": 600000, "unit_volume_ml": 275, "competitor_sku_1": "ABI004", "competitor_sku_2": "ABI009"},
    {"sku_id": "ABI009", "manufacturer": "AB InBev", "brand": "Beck's", "sku_name": "Beck's 330ml Can", "price_segment": "Value", "current_price_per_unit": 1.05, "elasticity": -2.3, "cannibalization_rate": 0.13, "profit_pct_per_ml": 0.15, "volume_2025_units": 520000, "unit_volume_ml": 330, "competitor_sku_1": "ABI008", "competitor_sku_2": "ABI004"},
    # Corona
    {"sku_id": "ABI010", "manufacturer": "AB InBev", "brand": "Corona", "sku_name": "Corona Extra 330ml Bottle", "price_segment": "Premium", "current_price_per_unit": 1.75, "elasticity": -1.3, "cannibalization_rate": 0.06, "profit_pct_per_ml": 0.25, "volume_2025_units": 700000, "unit_volume_ml": 330, "competitor_sku_1": "ABI005", "competitor_sku_2": "ABI011"},
    {"sku_id": "ABI011", "manufacturer": "AB InBev", "brand": "Corona", "sku_name": "Corona Extra 620ml Bottle", "price_segment": "Premium", "current_price_per_unit": 3.00, "elasticity": -1.1, "cannibalization_rate": 0.05, "profit_pct_per_ml": 0.26, "volume_2025_units": 280000, "unit_volume_ml": 620, "competitor_sku_1": "ABI010", "competitor_sku_2": "ABI006"},

    # ── Heineken ──────────────────────────────────────────────────────────
    # Heineken
    {"sku_id": "HEI001", "manufacturer": "Heineken", "brand": "Heineken", "sku_name": "Heineken 330ml Can", "price_segment": "Core", "current_price_per_unit": 1.25, "elasticity": -2.0, "cannibalization_rate": 0.11, "profit_pct_per_ml": 0.20, "volume_2025_units": 1100000, "unit_volume_ml": 330, "competitor_sku_1": "HEI002", "competitor_sku_2": "HEI003"},
    {"sku_id": "HEI002", "manufacturer": "Heineken", "brand": "Heineken", "sku_name": "Heineken 500ml Can", "price_segment": "Core", "current_price_per_unit": 1.85, "elasticity": -1.7, "cannibalization_rate": 0.09, "profit_pct_per_ml": 0.21, "volume_2025_units": 750000, "unit_volume_ml": 500, "competitor_sku_1": "HEI001", "competitor_sku_2": "HEI004"},
    {"sku_id": "HEI003", "manufacturer": "Heineken", "brand": "Heineken", "sku_name": "Heineken 330ml Bottle", "price_segment": "Core", "current_price_per_unit": 1.35, "elasticity": -1.9, "cannibalization_rate": 0.10, "profit_pct_per_ml": 0.20, "volume_2025_units": 680000, "unit_volume_ml": 330, "competitor_sku_1": "HEI001", "competitor_sku_2": "HEI002"},
    {"sku_id": "HEI004", "manufacturer": "Heineken", "brand": "Heineken", "sku_name": "Heineken Silver 330ml Can", "price_segment": "Premium", "current_price_per_unit": 1.45, "elasticity": -1.6, "cannibalization_rate": 0.08, "profit_pct_per_ml": 0.22, "volume_2025_units": 400000, "unit_volume_ml": 330, "competitor_sku_1": "HEI001", "competitor_sku_2": "HEI005"},
    # Amstel
    {"sku_id": "HEI005", "manufacturer": "Heineken", "brand": "Amstel", "sku_name": "Amstel 330ml Can", "price_segment": "Value", "current_price_per_unit": 1.00, "elasticity": -2.3, "cannibalization_rate": 0.13, "profit_pct_per_ml": 0.15, "volume_2025_units": 700000, "unit_volume_ml": 330, "competitor_sku_1": "HEI006", "competitor_sku_2": "HEI001"},
    {"sku_id": "HEI006", "manufacturer": "Heineken", "brand": "Amstel", "sku_name": "Amstel 500ml Can", "price_segment": "Value", "current_price_per_unit": 1.45, "elasticity": -2.1, "cannibalization_rate": 0.12, "profit_pct_per_ml": 0.16, "volume_2025_units": 480000, "unit_volume_ml": 500, "competitor_sku_1": "HEI005", "competitor_sku_2": "HEI001"},
    # Birra Moretti
    {"sku_id": "HEI007", "manufacturer": "Heineken", "brand": "Birra Moretti", "sku_name": "Birra Moretti 330ml Bottle", "price_segment": "Premium", "current_price_per_unit": 1.55, "elasticity": -1.4, "cannibalization_rate": 0.07, "profit_pct_per_ml": 0.23, "volume_2025_units": 500000, "unit_volume_ml": 330, "competitor_sku_1": "HEI008", "competitor_sku_2": "HEI004"},
    {"sku_id": "HEI008", "manufacturer": "Heineken", "brand": "Birra Moretti", "sku_name": "Birra Moretti 660ml Bottle", "price_segment": "Premium", "current_price_per_unit": 2.90, "elasticity": -1.2, "cannibalization_rate": 0.05, "profit_pct_per_ml": 0.25, "volume_2025_units": 300000, "unit_volume_ml": 660, "competitor_sku_1": "HEI007", "competitor_sku_2": "HEI004"},
    {"sku_id": "HEI009", "manufacturer": "Heineken", "brand": "Birra Moretti", "sku_name": "Birra Moretti 330ml Can", "price_segment": "Premium", "current_price_per_unit": 1.50, "elasticity": -1.5, "cannibalization_rate": 0.07, "profit_pct_per_ml": 0.22, "volume_2025_units": 420000, "unit_volume_ml": 330, "competitor_sku_1": "HEI007", "competitor_sku_2": "HEI008"},
    # Tiger
    {"sku_id": "HEI010", "manufacturer": "Heineken", "brand": "Tiger", "sku_name": "Tiger 330ml Can", "price_segment": "Core", "current_price_per_unit": 1.15, "elasticity": -2.1, "cannibalization_rate": 0.11, "profit_pct_per_ml": 0.18, "volume_2025_units": 380000, "unit_volume_ml": 330, "competitor_sku_1": "HEI001", "competitor_sku_2": "HEI005"},

    # ── Carlsberg ─────────────────────────────────────────────────────────
    # Carlsberg
    {"sku_id": "CRL001", "manufacturer": "Carlsberg", "brand": "Carlsberg", "sku_name": "Carlsberg 330ml Can", "price_segment": "Core", "current_price_per_unit": 1.15, "elasticity": -2.2, "cannibalization_rate": 0.12, "profit_pct_per_ml": 0.17, "volume_2025_units": 950000, "unit_volume_ml": 330, "competitor_sku_1": "CRL002", "competitor_sku_2": "CRL003"},
    {"sku_id": "CRL002", "manufacturer": "Carlsberg", "brand": "Carlsberg", "sku_name": "Carlsberg 500ml Can", "price_segment": "Core", "current_price_per_unit": 1.70, "elasticity": -1.9, "cannibalization_rate": 0.10, "profit_pct_per_ml": 0.18, "volume_2025_units": 650000, "unit_volume_ml": 500, "competitor_sku_1": "CRL001", "competitor_sku_2": "CRL004"},
    {"sku_id": "CRL003", "manufacturer": "Carlsberg", "brand": "Carlsberg", "sku_name": "Carlsberg 330ml Bottle", "price_segment": "Core", "current_price_per_unit": 1.20, "elasticity": -2.0, "cannibalization_rate": 0.11, "profit_pct_per_ml": 0.17, "volume_2025_units": 520000, "unit_volume_ml": 330, "competitor_sku_1": "CRL001", "competitor_sku_2": "CRL002"},
    {"sku_id": "CRL004", "manufacturer": "Carlsberg", "brand": "Carlsberg", "sku_name": "Carlsberg Export 500ml Can", "price_segment": "Core", "current_price_per_unit": 1.80, "elasticity": -1.8, "cannibalization_rate": 0.09, "profit_pct_per_ml": 0.19, "volume_2025_units": 380000, "unit_volume_ml": 500, "competitor_sku_1": "CRL002", "competitor_sku_2": "CRL001"},
    # San Miguel
    {"sku_id": "CRL005", "manufacturer": "Carlsberg", "brand": "San Miguel", "sku_name": "San Miguel 330ml Bottle", "price_segment": "Premium", "current_price_per_unit": 1.50, "elasticity": -1.6, "cannibalization_rate": 0.08, "profit_pct_per_ml": 0.21, "volume_2025_units": 550000, "unit_volume_ml": 330, "competitor_sku_1": "CRL006", "competitor_sku_2": "CRL001"},
    {"sku_id": "CRL006", "manufacturer": "Carlsberg", "brand": "San Miguel", "sku_name": "San Miguel 660ml Bottle", "price_segment": "Premium", "current_price_per_unit": 2.75, "elasticity": -1.3, "cannibalization_rate": 0.06, "profit_pct_per_ml": 0.23, "volume_2025_units": 280000, "unit_volume_ml": 660, "competitor_sku_1": "CRL005", "competitor_sku_2": "CRL007"},
    {"sku_id": "CRL007", "manufacturer": "Carlsberg", "brand": "San Miguel", "sku_name": "San Miguel 330ml Can", "price_segment": "Premium", "current_price_per_unit": 1.45, "elasticity": -1.7, "cannibalization_rate": 0.08, "profit_pct_per_ml": 0.21, "volume_2025_units": 430000, "unit_volume_ml": 330, "competitor_sku_1": "CRL005", "competitor_sku_2": "CRL006"},
    # Kronenbourg
    {"sku_id": "CRL008", "manufacturer": "Carlsberg", "brand": "Kronenbourg", "sku_name": "Kronenbourg 1664 330ml Can", "price_segment": "Value", "current_price_per_unit": 1.05, "elasticity": -2.4, "cannibalization_rate": 0.14, "profit_pct_per_ml": 0.16, "volume_2025_units": 480000, "unit_volume_ml": 330, "competitor_sku_1": "CRL001", "competitor_sku_2": "CRL009"},
    {"sku_id": "CRL009", "manufacturer": "Carlsberg", "brand": "Kronenbourg", "sku_name": "Kronenbourg 1664 500ml Can", "price_segment": "Value", "current_price_per_unit": 1.55, "elasticity": -2.2, "cannibalization_rate": 0.13, "profit_pct_per_ml": 0.17, "volume_2025_units": 340000, "unit_volume_ml": 500, "competitor_sku_1": "CRL008", "competitor_sku_2": "CRL001"},
    # Somersby
    {"sku_id": "CRL010", "manufacturer": "Carlsberg", "brand": "Somersby", "sku_name": "Somersby Apple Cider 330ml Can", "price_segment": "Core", "current_price_per_unit": 1.30, "elasticity": -1.9, "cannibalization_rate": 0.10, "profit_pct_per_ml": 0.19, "volume_2025_units": 310000, "unit_volume_ml": 330, "competitor_sku_1": "CRL001", "competitor_sku_2": "CRL005"},

    # ── Molson Coors ──────────────────────────────────────────────────────
    # Coors
    {"sku_id": "MC001", "manufacturer": "Molson Coors", "brand": "Coors", "sku_name": "Coors Light 330ml Can", "price_segment": "Value", "current_price_per_unit": 1.10, "elasticity": -2.3, "cannibalization_rate": 0.13, "profit_pct_per_ml": 0.16, "volume_2025_units": 820000, "unit_volume_ml": 330, "competitor_sku_1": "MC002", "competitor_sku_2": "MC003"},
    {"sku_id": "MC002", "manufacturer": "Molson Coors", "brand": "Coors", "sku_name": "Coors Light 500ml Can", "price_segment": "Value", "current_price_per_unit": 1.65, "elasticity": -2.0, "cannibalization_rate": 0.11, "profit_pct_per_ml": 0.17, "volume_2025_units": 560000, "unit_volume_ml": 500, "competitor_sku_1": "MC001", "competitor_sku_2": "MC004"},
    {"sku_id": "MC003", "manufacturer": "Molson Coors", "brand": "Coors", "sku_name": "Coors Original 330ml Can", "price_segment": "Core", "current_price_per_unit": 1.25, "elasticity": -2.1, "cannibalization_rate": 0.12, "profit_pct_per_ml": 0.18, "volume_2025_units": 450000, "unit_volume_ml": 330, "competitor_sku_1": "MC001", "competitor_sku_2": "MC002"},
    # Carling
    {"sku_id": "MC004", "manufacturer": "Molson Coors", "brand": "Carling", "sku_name": "Carling 500ml Can", "price_segment": "Value", "current_price_per_unit": 1.50, "elasticity": -2.1, "cannibalization_rate": 0.12, "profit_pct_per_ml": 0.15, "volume_2025_units": 1000000, "unit_volume_ml": 500, "competitor_sku_1": "MC001", "competitor_sku_2": "MC005"},
    {"sku_id": "MC005", "manufacturer": "Molson Coors", "brand": "Carling", "sku_name": "Carling 330ml Can", "price_segment": "Value", "current_price_per_unit": 1.05, "elasticity": -2.3, "cannibalization_rate": 0.13, "profit_pct_per_ml": 0.14, "volume_2025_units": 720000, "unit_volume_ml": 330, "competitor_sku_1": "MC004", "competitor_sku_2": "MC001"},
    {"sku_id": "MC006", "manufacturer": "Molson Coors", "brand": "Carling", "sku_name": "Carling 660ml Bottle", "price_segment": "Value", "current_price_per_unit": 1.85, "elasticity": -1.9, "cannibalization_rate": 0.11, "profit_pct_per_ml": 0.15, "volume_2025_units": 380000, "unit_volume_ml": 660, "competitor_sku_1": "MC004", "competitor_sku_2": "MC005"},
    # Cobra
    {"sku_id": "MC007", "manufacturer": "Molson Coors", "brand": "Cobra", "sku_name": "Cobra 330ml Bottle", "price_segment": "Premium", "current_price_per_unit": 1.45, "elasticity": -1.7, "cannibalization_rate": 0.08, "profit_pct_per_ml": 0.20, "volume_2025_units": 420000, "unit_volume_ml": 330, "competitor_sku_1": "MC008", "competitor_sku_2": "MC001"},
    {"sku_id": "MC008", "manufacturer": "Molson Coors", "brand": "Cobra", "sku_name": "Cobra 660ml Bottle", "price_segment": "Premium", "current_price_per_unit": 2.60, "elasticity": -1.4, "cannibalization_rate": 0.06, "profit_pct_per_ml": 0.22, "volume_2025_units": 220000, "unit_volume_ml": 660, "competitor_sku_1": "MC007", "competitor_sku_2": "MC004"},
    # Madri
    {"sku_id": "MC009", "manufacturer": "Molson Coors", "brand": "Madri", "sku_name": "Madri Excepcional 330ml Can", "price_segment": "Premium", "current_price_per_unit": 1.55, "elasticity": -1.5, "cannibalization_rate": 0.07, "profit_pct_per_ml": 0.23, "volume_2025_units": 580000, "unit_volume_ml": 330, "competitor_sku_1": "MC010", "competitor_sku_2": "MC007"},
    {"sku_id": "MC010", "manufacturer": "Molson Coors", "brand": "Madri", "sku_name": "Madri Excepcional 660ml Bottle", "price_segment": "Premium", "current_price_per_unit": 2.85, "elasticity": -1.3, "cannibalization_rate": 0.05, "profit_pct_per_ml": 0.24, "volume_2025_units": 310000, "unit_volume_ml": 660, "competitor_sku_1": "MC009", "competitor_sku_2": "MC008"},
    # Staropramen
    {"sku_id": "MC011", "manufacturer": "Molson Coors", "brand": "Staropramen", "sku_name": "Staropramen 330ml Can", "price_segment": "Core", "current_price_per_unit": 1.30, "elasticity": -1.8, "cannibalization_rate": 0.09, "profit_pct_per_ml": 0.19, "volume_2025_units": 350000, "unit_volume_ml": 330, "competitor_sku_1": "MC003", "competitor_sku_2": "MC009"},
]

df = pd.DataFrame(skus)
output_path = "data/full_portfolio.xlsx"
df.to_excel(output_path, index=False, sheet_name="SKU Portfolio")
print(f"Created {output_path} with {len(df)} SKUs")
print(f"Manufacturers: {df['manufacturer'].nunique()} — {', '.join(sorted(df['manufacturer'].unique()))}")
print(f"Brands: {df['brand'].nunique()}")
print(f"Segments: {', '.join(sorted(df['price_segment'].unique()))}")
